"""Game constants to replace magic numbers."""

INITIAL_BALANCE = 300
LAP_BONUS = 100
CAUTIOUS_THRESHOLD = 80
DEMANDING_RENT_THRESHOLD = 50
BOARD_SIZE = 20
BASE_PROPERTY_PRICE = 100
PRICE_MULTIPLIER = 10
BASE_RENT = 10
RENT_MULTIPLIER = 5
MAX_ROUNDS = 1000